FROM node:8

RUN mkdir -p /usr/src/app/

WORKDIR /usr/src/app/

COPY package.json package-lock.json tsconfig.json ./

RUN npm install

RUN mkdir -p api config src/api src/common
COPY ./api/ ./api/
COPY ./config/ ./config/
COPY ./src/alarm/ ./src/alarm/
COPY ./src/common/ ./src/common/

RUN ./node_modules/.bin/tsc

ARG NODE_ENV="production"
ENV NODE_ENV $NODE_ENV

CMD [ "npm", "run", "alarm" ]
