version: "2"

services:

  rest-api:
    image: node-api
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "3000:3000"

  alarm-server:
    image: node-alarm
    build:
      context: .
      dockerfile: Dockerfile-alarm
