FROM node:8-alpine

RUN mkdir -p /usr/src/app/

WORKDIR /usr/src/app/

COPY package.json package-lock.json tsconfig.json ./

RUN npm ci

RUN mkdir -p api config src/api src/common
COPY ./api/ ./api/
COPY ./config/ ./config/
COPY ./src/common/ ./src/common/
COPY ./src/api/ ./src/api/

RUN ./node_modules/.bin/tsc

ARG NODE_ENV="production"
ENV NODE_ENV $NODE_ENV

ARG PORT=3000
ENV PORT $PORT
EXPOSE $PORT

CMD [ "npm", "start" ]
