FROM node:8-alpine

RUN mkdir -p /usr/src/app/

WORKDIR /usr/src/app/

COPY package.json package-lock.json tsconfig.json ./

RUN npm ci

RUN mkdir -p api config src/api src/common
COPY ./api/ ./api/
COPY ./config/ ./config/
COPY ./src/common/ ./src/common/
COPY ./src/alarm/ ./src/alarm/

RUN ./node_modules/.bin/tsc

CMD [ "npm", "run", "alarm" ]
