FROM node:8

RUN mkdir -p /usr/src/app/

WORKDIR /usr/src/app/

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN ./node_modules/.bin/tsc

ARG NODE_ENV="production"
ENV NODE_ENV $NODE_ENV

ARG PORT=3000
ENV PORT $PORT
EXPOSE $PORT

CMD [ "npm", "start" ]
