mongoUrl: mongodb://127.0.0.1:27017
database: alarmServer
next_execute_delay_min: 2018-05-20T13:30:17.738Z
schedule_check_new_alarms: "*/1 * * * * *"
port: 3000
slack_webhook_url: "https://hooks.slack.com/services/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"
