mongoUrl: mongodb://127.0.0.1:27017
database: alarmServer
cron_check_alarms: "*/1 * * * * *"
slack_webhook_url: "https://hooks.slack.com/services/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"
slack_channel: "#general"
slack_username: "webhookbot"
slack_icon_emoji: ":ghost:"
