mongoUrl: mongodb://slack-alarm-service_mongo-db_1:27017
database: alarmServer
database_connection_retries: 10
database_connection_wait: 6000
unique_alert_times: false
cron_check_alarms: "*/1 * * * * *"
