mongoUrl: mongodb://slack-alarm-service_mongo-db_1:27017
database: alarmServer
database_connection_retries: 10
database_connection_wait: 6000
cron_check_alarms: "*/1 * * * * *"
slack_webhook_url: "https://hooks.slack.com/services/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"
slack_channel: "#general"
slack_username: "webhookbot"
slack_icon_emoji: ":ghost:"
